DROP TABLE IF EXISTS PROFILE;

CREATE TABLE PROFILE (
    NAME VARCHAR(10) NOT NULL,
    JANUARY DOUBLE NOT NULL,
	FEBRUARY DOUBLE NOT NULL,
	MARCH DOUBLE NOT NULL,
	APRIL DOUBLE NOT NULL,
	MAY DOUBLE NOT NULL,
	JUNE DOUBLE NOT NULL,
	JULY DOUBLE NOT NULL,
	AUGUST DOUBLE NOT NULL,
	SEPTEMBER DOUBLE NOT NULL,
	OCTOBER DOUBLE NOT NULL,
	NOVEMBER DOUBLE NOT NULL,
	DECEMBER DOUBLE NOT NULL,
	UNIQUE UQ_PROFILE_1 (NAME), 
	PRIMARY KEY (NAME)
);
